"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['savetowiki.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'plist': dict(
    CFBundleName='savetowiki',
    CFBundleIdentifier='de.lostpackets.savetowiki',
    CFBundleURLTypes=[dict(
        CFBundleURLName='wikisave',
        CFBundleURLSchemes=['wikisave'],
    )],
),
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
